### ISSUE TITLE
Expand on Chapter 01

### ISSUE THREAD

**Issue by xsawyerx** [rgs/p5-intelligible-unicode#2]
Chapter 01 shouldn't really be just *Perl strings*, but should, in fact, be an introduction. It should explain Perl strings as it does now, but provide a few examples on what this means in practice.

It should show `encode` and `decode` from `Encode` module.

**Comment by rgs** [comment]
I don't like this approach very much because I tried to be very gradual in introducing concepts, so Encode is introduced after the reader has a grasp of what encoding and decoding mean, which I explain in chapters 3 and 4. However I have extended a bit chapter 1 to mention the syntax \x{...} that I'll use later. Also Xavier added more explanations.

I now wonder if I should permute chapters 2 and 3.

**Comment by xsawyerx** [comment]
Fair enough. Closing the issue. :)
